### ISSUE TITLE
Allow setting controller parameters with vector of size 1

### ISSUE THREAD

**Issue by domire8** [aica-technology/control-libraries#144]
At the moment, controller parameters like stiffness and damping can be set with either a double, a vector, or a matrix. If it's a vector, the size has to correspond to the length of the diagonal, if it's a matrix, the size has to correspond to the controller matrix too. If you provide a double, the values on the diagonal will be set to that value. It would be nice to do that as well if a vector of size 1 is provided. This would allow modulo controllers to set those parameters more easily.

Would you agree @eeberhard ?

**Comment by eeberhard** [comment]
Good with me, it would allow more flexibility without a huge amount of additional logic.
