### ISSUE TITLE
Add utilities to map from parameter type to the type label

### ISSUE THREAD

**Issue by domire8** [aica-technology/control-libraries#152]
`state_representation` has the `Parameter` object that can have different `type`s, see the available types [here](https://github.com/aica-technology/control-libraries/blob/main/source/state_representation/include/state_representation/parameters/ParameterType.hpp). It would be great if we could have a human readable string associated with each parameter type such that we can be more precise when logging errors. For that, I propose to add under the parameters namespace some utilities:
```cpp
/**
 * @brief Get a map of parameter type labels with the corresponding type
 * @return a map of parameter type labels with the corresponding type
 */
const std::map<std::string, ParameterType>& map();

/**
 * @brief Get the parameter type from the label
 * @param label The parameter type label (lowercase)
 * @throws std::out_of_range exception if the label has no corresponding type
 * @return the parameter type
 */
ParameterType parameter_type(const std::string& label);

/**
 * @brief Get the parameter type label from the type
 * @param id The parameter type
 * @return the parameter type label
 */
std::string label(ParameterType parameter_type);
```

**Comment by bpapaspyros** [comment]
@domire8 I am not quite confident with the naming convention I followed (which is altered from the example), so let me know if this needs adjustments. There is also different conventions followed between DSE and the StateType for example.
