### ISSUE TITLE
Add FCL and Octamap dependencies for collsion detection Support

### ISSUE THREAD

**Issue by yrh012** [aica-technology/control-libraries#160]
In this issue, we aim to add the Flexible Collisions Library (FCL) and Octomap Libraries as package dependencies. This integration will enable us to leverage Pinocchio's collision detection features within the `robot_model` on Control Libraries.

**Comment by domire8** [comment]
https://github.com/aica-technology/control-libraries/commit/940b05a8147a00828f64f31bcddeb1e74aff1945

First attempt
