### ISSUE TITLE
Handle hard-coded locations in test urdfs

### ISSUE THREAD

**Issue by yrh012** [aica-technology/control-libraries#165]
The UR5e URDFs, utilized in both the Python and C++ test codes, currently have hardcoded path locations. These path locations should be dynamically updated to reflect the actual file locations of the collision meshes without prior assumption on the global path.

**Comment by domire8** [comment]
Haha wanted to tackle this but realized it's already done right @yrh012 ?

**Comment by yrh012** [comment]
> Haha wanted to tackle this but realized it's already done right @yrh012 ?

Yes indeed! Now with the package path resolver callback, the consumer of `robot_model::Model` will have to define how the package resolves. In the case of the tests, a dummy callback can define the actual paths of the packages and that resolves the issue.
