### ISSUE TITLE
Treat operator * and *= differently for CartesianState

### ISSUE THREAD

**Issue by buschbapti** [aica-technology/control-libraries#22]
The `CartesianState` is a specific case for operators as it represent the biggest ensemble of any derived. At the moment, the `operator*` and `operator*` restrict operations with derived classes and always return the type of right hand side attribute.

For `CartesianState` this should not be the case. Any operations with a derived class should be accepted as the data to make that operation possible are there. Plus, in order to not loose information, the result should always be a `CartesianState`.

This should make operations with moving reference frame possible.

**Comment by buschbapti** [comment]
@eeberhard and @domire8 what are your opinions on this?

**Comment by eeberhard** [comment]
Yes, I agree with your reasoning. I would summarize it as follows:

`CartesianState * CartesianAny` should be treated as `CartesianState * CartesianState(CartesianAny)`

Defined like that, the implementation should be quite straightforward. Though, if you define these operators in `CartesianState.hpp` then it will require the forward declaration of the derived classes. I think this should work but there's a chance it leads to circular dependencies.

**Comment by buschbapti** [comment]
Merging of #28 in the refactor branch allows me to close this issue.
