### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by domire8** [aica-technology/control-libraries#49]
As we progressed so much towards the 7.0 release and trying to solidify the operators and such, we should update the documentation as well.

**Comment by eeberhard** [comment]
Some relevant documentation areas to update:
 
- [ ] Function and compatibility of + / - operators
- [ ] Function and compatibility of * operators
- [ ] Clarification of what CartesianTwist actually represents (#88)
- [ ] Similarly, clarification of what CartesianWrench represents
- [ ] Special attention to Wrench in case of transform and inverse
